### ISSUE TITLE
The training logic seems wrong

### ISSUE THREAD

**Issue by 121898** [ShuoYang-1998/ICLR2021-Oral_Distribution_Calibration#2]
The code in the train.py seems wrong, with regard to the "resume" part, it doesn't make sense to load checkpoints no matter whether "resume" is stored to True. Why should do the "rotation" replacement when I set "resume" to False？Is it put in the wrong place? Also, running this code will give a "checkpoint not found" error.

**Comment by ShuoYang-1998** [comment]
Sorry, all parts about 'rotation' or 'resume' were borrowed from the original codebase, which is totally irrelevant to our work. I already delete those parts from the train.py.

Actually, all our algorithm is built upon the extracted features, the training procedure and the extracted features are all the same as the reference work 'S2M2' and their code [https://github.com/nupurkmr9/S2M2_fewshot](url). You can reproduce our work by applying evaluate_DC.py on their extracted features. Thanks!
