### ISSUE TITLE
关于模型训练的若干问题

### ISSUE THREAD

**Issue by zrsgnl** [ShuoYang-1998/ICLR2021-Oral_Distribution_Calibration#4]
作者您好，我用您提供的pretrain模型，可以复现出论文上的性能。
但是我严格按照readme中的步骤来训练出来的模型，与论文上的性能相差甚远（在CUB数据集上只有70% Acc，miniImagenet上只有58% Acc）。并且训练了多次，这个问题依然无法解决。
请问这个问题该如何解决？

**Comment by ShuoYang-1998** [comment]
你好，我们的网络训练过程与参考工作S2M2完全一致，预训练模型和提取的特征也都是从S2M2的GitHub获得，你可以参考他们的训练过程或者使用他们提供的预训练模型。
[https://github.com/nupurkmr9/S2M2_fewshot](url)

**Comment by zrsgnl** [comment]
那您有自己训过这个S2M2模型吗？并且得到一致的性能

**Comment by ShuoYang-1998** [comment]
是可以的，你在mini上的58%是经过distribution_calibration之后的性能吗？直接用提取的特征去训练线性分类器效果确实是56-58左右，经过distribution calibration之后能达到68%。

**Comment by zrsgnl** [comment]
是的经过了distribution_calibration的，完全git clone您的代码下来，几乎不做任何修改，不知为何就是无法复现出paper上的性能，直到您给出了pretrain_model的参数才能复现出。
您的工作非常新颖，我在openreview的时候就已经关注了。还有一个问题就是在《Close Look》的baseline++的基础上的性能提升，Table6上说在miniImagenet的数据集上，baseline++(Conv4)的性能可以从48.24提升到61.24，但是我复现出来的性能是53%，只提升了5个点左右。您后续是否有精力，提供可复现paper性能的在baseline++上训的官方代码呢？

**Comment by ShuoYang-1998** [comment]
你好，在训练网络的时候需要添加一个参数--train_aug。

**Comment by stpiamcee** [comment]
您好，下载了预训练模型，为什么运行train.py的时候报错   invalid literal for int() with base 10: 'pretrained_model'

**Comment by ljjcoder** [comment]
@ShuoYang-1998  @zrsgnl 请问是否能提供一下json文件,imagenet文件过于庞大，下载制作数据集难度太大

**Comment by ljjcoder** [comment]
@ShuoYang-1998 @zrsgnl 我按照S2M2的方法训练了rotation loss的模型，然后按照您的代码提取特征并且测试也只得到0.58左右的准确率，不知道这是什么原因导致的
