### ISSUE TITLE
经过校准分布采样到的样本特征存在nan值，导致无法训练分类器

### ISSUE THREAD

**Issue by aiyolo** [ShuoYang-1998/ICLR2021-Oral_Distribution_Calibration#5]
非常感谢您的出色工作。
我使用另外一个预训练网络提取特征之后，经过校准分布采样到的样本特征存在nan值，导致无法训练分类器，不知道这一点有什么好的解决方法？（问题似乎不在于我的预训练网络，因为我的预训练网络在其他方法上进行测试能表现正常。）
![image](https://user-images.githubusercontent.com/12464091/104949410-ddeda580-59f9-11eb-9911-f43ed9cbf0f0.png)

**Comment by ShuoYang-1998** [comment]
Why you got NaN value from a Gaussian distribution? Please check your code or features (note that the Turkey transformation requires all input features non-negative)

**Comment by TsingJyujing** [comment]
> Why you got NaN value from a Gaussian distribution? Please check your code or features (note that the Turkey transformation requires all input features non-negative)

I tested the code on my local machine, which caused by cov matrix is **not positive-semidefinite**. Anyway, the code doesn't work.

I guess it's caused by the sample in some class less than dimension.
A simple way to solve this problem is strengthen the numerical stability.
Like add en eye-matrix on cov, but I'm not sure will the performance still as good as before. 😓

**Comment by darkliang** [comment]
> Why you got NaN value from a Gaussian distribution? Please check your code or features (note that the Turkey transformation requires all input features non-negative)

Hi, did you mean we should do Tukey transformation in the base classes statistics phase also?

**Comment by andrew-miao** [comment]
> > Why you got NaN value from a Gaussian distribution? Please check your code or features (note that the Turkey transformation requires all input features non-negative)
> 
> I tested the code on my local machine, which caused by cov matrix is **not positive-semidefinite**. Anyway, the code doesn't work.
> 
> I guess it's caused by the sample in some class less than dimension.
> A simple way to solve this problem is to strengthen the numerical stability.
> E.X. add en eye-matrix on cov:
> 
> ```python
> calibrated_cov = np.mean(np.array(base_cov)[index], axis=0) + np.eye(len(calibrated_mean)) * eps + alpha
> ```
> 
> But I'm not sure will the performance still as good as before. 😓
> I only tested 100 tasks on CUB dataset (query=15,way=5,shot=1), the Acc is around 0.803 after I set eps=0.01.

Hi, sorry to bother you, I have another question, why calibrated_cov is a non-PSD matrix?

calibrated_cov = 1/K * sum(selected base cov), where K is the hyperparameter of topk operator. Base covariance matrices are PSD matrices, so why the sum of PSD matrices will be a non-PSD matrix?

**Comment by TsingJyujing** [comment]
@andrew-miao sorry I haven't deeply investigated the project and already forgot some details, but I guess it's not a theroitical problem but some numerical calculations bug...
Let's investigate it later...
