### ISSUE TITLE
low execution speed

### ISSUE THREAD

**Issue by zhouyuan888888** [ShuoYang-1998/ICLR2021-Oral_Distribution_Calibration#8]
I find when generating 10000 tasks, the speed is very slow (generating 300 tasks costs about 7 hours). So, how to speed up this process? Thank you for your help~!

**Comment by LinglanZhao** [comment]
Maybe you can try my re-implementation #3 which is faster (about 90min for 2000 tasks in 1-shot case). You can also use less tasks during testing.

**Comment by zhouyuan888888** [comment]
@LinglanZhao  ok! ！！
